// ---------------------------------------------------------------------------
// ClawMind — Memory Manager with Embedding-Based Semantic Retrieval
// ---------------------------------------------------------------------------
// Retrieves memories using cosine similarity over embedding vectors
// generated by all-MiniLM-L6-v2. Falls back to keyword matching if
// embeddings are unavailable.
// ---------------------------------------------------------------------------

import { mockMemories } from "@/lib/demo/mock-memory";
import { AnalysisReport, MemoryRecord } from "@/lib/types";
import {
  appendPersistentMemory,
  readPersistentMemories,
} from "@/lib/memory/persistent-memory-store";
import {
  generateEmbedding,
  findTopK,
  isEmbeddingReady,
} from "@/lib/memory/embeddings";

type ScoredMemory = {
  memory: MemoryRecord;
  score: number;
  similarityScore?: number;
};

function normalizeText(text: string): string {
  return text.toLowerCase().replace(/[^a-z0-9\s]/g, " ");
}

function extractKeywords(text: string): string[] {
  const stopWords = new Set([
    "this", "that", "with", "from", "into", "over", "under", "across",
    "protocol", "project", "analyze", "agent", "system", "using", "uses",
    "while", "should", "would", "could", "about", "through", "between",
    "multiple",
  ]);

  return normalizeText(text)
    .split(/\s+/)
    .map((word) => word.trim())
    .filter((word) => word.length >= 4)
    .filter((word) => !stopWords.has(word));
}

/**
 * Keyword-based scoring (fallback when embeddings unavailable).
 */
function scoreMemoryByKeywords(task: string, memory: MemoryRecord): number {
  const keywords = extractKeywords(task);

  const searchableMemoryText = normalizeText(
    [
      memory.task,
      memory.summary,
      memory.recommendation,
      String(memory.score),
      memory.storageUri ?? "",
      ...memory.risks,
    ].join(" "),
  );

  const keywordScore = keywords.reduce((total, keyword) => {
    return searchableMemoryText.includes(keyword) ? total + 1 : total;
  }, 0);

  const riskBoost = memory.risks.some((risk) => {
    return normalizeText(task).includes(normalizeText(risk));
  })
    ? 3
    : 0;

  const storageBoost = memory.storageUri?.startsWith("0g://") ? 1 : 0;

  return keywordScore + riskBoost + storageBoost;
}

function deduplicateRelevantMemories(memories: MemoryRecord[]): MemoryRecord[] {
  const seenKeys = new Set<string>();
  const deduplicated: MemoryRecord[] = [];

  for (const memory of memories) {
    const normalizedTask = normalizeText(memory.task);
    const storageKey =
      memory.storageUri && memory.storageUri.trim().length > 0
        ? `storage:${memory.storageUri.trim()}`
        : "";

    const key =
      normalizedTask.length > 0
        ? `task:${normalizedTask}`
        : storageKey || `id:${memory.id}`;

    if (!seenKeys.has(key)) {
      seenKeys.add(key);
      deduplicated.push(memory);
    }
  }

  return deduplicated;
}

export async function getAllMemories(): Promise<MemoryRecord[]> {
  const persistentMemories = await readPersistentMemories();

  const seenIds = new Set<string>();
  const allMemories: MemoryRecord[] = [];

  for (const memory of [...persistentMemories, ...mockMemories]) {
    if (!seenIds.has(memory.id)) {
      seenIds.add(memory.id);
      allMemories.push(memory);
    }
  }

  return deduplicateRelevantMemories(allMemories);
}

/**
 * Get relevant memories using embedding-based semantic retrieval.
 *
 * Strategy:
 * 1. Generate embedding for the query task
 * 2. If embeddings are available on stored memories → cosine similarity top-k
 * 3. If not → generate embeddings for memories that lack them, then retrieve
 * 4. Fallback: keyword-based scoring if embedding model fails
 */
export async function getRelevantMemories(task: string): Promise<MemoryRecord[]> {
  const allMemories = await getAllMemories();

  if (allMemories.length === 0) {
    return [];
  }

  // Try embedding-based retrieval
  try {
    const queryEmbedding = await generateEmbedding(task);

    // Check if any stored memories have embeddings
    const memoriesWithEmbeddings = allMemories.filter(
      (m) => m.embedding && m.embedding.length > 0
    );
    const memoriesWithoutEmbeddings = allMemories.filter(
      (m) => !m.embedding || m.embedding.length === 0
    );

    // Generate embeddings for memories that lack them (lazy backfill)
    if (memoriesWithoutEmbeddings.length > 0 && memoriesWithEmbeddings.length === 0) {
      console.log(
        `[Memory] Generating embeddings for ${memoriesWithoutEmbeddings.length} memories (lazy backfill)...`
      );

      // Generate embeddings in batch (limit to first 20 for performance)
      const toEmbed = memoriesWithoutEmbeddings.slice(0, 20);
      for (const memory of toEmbed) {
        try {
          const embedding = await generateEmbedding(
            `${memory.task} ${memory.summary}`
          );
          memory.embedding = embedding;
        } catch {
          // Skip this memory if embedding fails
        }
      }
    }

    // Re-check after backfill
    const embeddableMemories = allMemories.filter(
      (m) => m.embedding && m.embedding.length > 0
    );

    if (embeddableMemories.length > 0) {
      const topK = findTopK(queryEmbedding, embeddableMemories, 3);

      console.log(
        `[Memory] Semantic retrieval: top ${topK.length} memories (scores: ${topK
          .map((m) => m.similarityScore.toFixed(2))
          .join(", ")})`
      );

      // Return memories with similarity scores
      return topK.map((m) => ({
        ...m,
        similarityScore: m.similarityScore,
      }));
    }
  } catch (error) {
    console.warn("[Memory] Embedding-based retrieval failed, falling back to keywords:", error);
  }

  // Fallback: keyword-based scoring
  const scoredMemories: ScoredMemory[] = allMemories.map((memory) => ({
    memory,
    score: scoreMemoryByKeywords(task, memory),
  }));

  const rankedMemories = scoredMemories
    .filter((item) => item.score > 0)
    .sort((a, b) => b.score - a.score)
    .map((item) => item.memory);

  const relevantMemories = deduplicateRelevantMemories(rankedMemories).slice(0, 3);

  if (relevantMemories.length > 0) {
    return relevantMemories;
  }

  return deduplicateRelevantMemories(allMemories).slice(0, 2);
}

export function formatMemoryContext(memories: MemoryRecord[]): string {
  if (memories.length === 0) {
    return "No relevant memories found.";
  }

  return memories
    .map((memory) => {
      const similarityStr = memory.similarityScore
        ? `\nSimilarity: ${(memory.similarityScore * 100).toFixed(1)}%`
        : "";

      return [
        `Memory ID: ${memory.id}`,
        `Task: ${memory.task}`,
        `Summary: ${memory.summary}`,
        `Risks: ${memory.risks.join(", ")}`,
        `Recommendation: ${memory.recommendation}`,
        `Score: ${memory.score}`,
        `Storage URI: ${memory.storageUri || "not available"}`,
        similarityStr,
      ].join("\n");
    })
    .join("\n\n");
}

export async function saveGeneratedMemoryRecord(input: {
  task: string;
  report: AnalysisReport;
  storageUri?: string;
}): Promise<{
  memory: MemoryRecord;
  memories: MemoryRecord[];
}> {
  const createdAt = new Date().toISOString();

  // Generate embedding for the new memory
  let embedding: number[] | undefined;
  try {
    embedding = await generateEmbedding(`${input.task} ${input.report.summary}`);
    console.log(`[Memory] Generated embedding for new memory (dim=${embedding.length})`);
  } catch (error) {
    console.warn("[Memory] Failed to generate embedding for new memory:", error);
  }

  const memory: MemoryRecord = {
    id: `mem_generated_${Date.now()}`,
    task: input.task,
    summary: input.report.summary,
    risks: input.report.risks.map((risk) => risk.title),
    recommendation: input.report.recommendation,
    score: input.report.score,
    storageUri: input.storageUri,
    createdAt,
    embedding,
  };

  const memories = await appendPersistentMemory(memory);

  return {
    memory,
    memories,
  };
}
